### ISSUE TITLE
Chained ORM selectors not reflecting changes?

### ISSUE THREAD

**Issue by nealoke** [redux-orm/redux-orm#148]
I've just discovered that chained selectors do not update eventhough the last in the chain has changed. 

The following code does not reflect the changes when the `account` is being updated.
```javascript
/**
 * Return the session client
 * @return 	{Object} 		Client
 */
export const getSessionClient = createSelector(orm, getOrm, (session) => {
	return session.Session.first().client.ref;
});

/**
 * Get all accounts of the active client
 * @return {Object} Orm queryset
 */
export const getClientAccountsQuerySet = createSelector(orm, getOrm, getSessionClient, (session, client) => {
	return session.Client.withId(client.id).accounts.all();
});

/**
 * Return all accounts enhanced with data of questions
 * @return {Array} Accounts
 */
export const getAccounts = createSelector(orm, getOrm, getClientAccountsQuerySet, (session, clientAccountsQuerySet) => {
	return clientAccountsQuerySet.toModelArray().map(accountModel => ({
		...accountModel.ref,
		questions: accountModel.questions.toRefArray()
	}));
});
```

I've tried to create a single selector and this is working. But to my understanding the whole purpose of chaining selectors is so you don't have code duplication and it works faster. (tell me if i'm wrong :p )

```javascript
export const getAccounts = createSelector(orm, getOrm, (session) => {
	return session.Client.withId(session.Session.first().client.ref.id).accounts.all().toModelArray().map(accountModel => ({
		...accountModel.ref,
		questions: accountModel.questions.toRefArray()
	}));
});
```

**Comment by nealoke** [comment]
@markerikson @NathanBWaters any input on this would be very appreciated 🥇

**Comment by markerikson** [comment]
I have not actually used selectors with Redux-ORM yet myself, so I don't have any immediate suggestions.

**Comment by NathanBWaters** [comment]
I'm in the same boat in that I haven't used a selector with Redux-ORM.
So your problem is that the chained selector isn't updated on a ReduxORM model being updated, right?  Have you confirmed that the input selectors are activating?
Also, is this behavior replicated across all of your models and they're attributes or just this model?

**Comment by nealoke** [comment]
@markerikson  @NathanBWaters I've just checked and I can confirm that this is not just the selector I first tried. Just to confirm I am thinking of the chaining in the correct way right? 

So to rephrase, in the example I have the `getClientAccountsQuerySet` selector which has `getSessionClient` as an input for the selector. When the `accounts` of the `Client` model changes it does not retrigger this function as the `getSessionClient` did not change.

**Comment by markerikson** [comment]
@nealoke : what does `Client.accounts` look like?  Is it a relation of `Client`, and in particular, a `many` relation?  If so, then I would indeed expect your final selector to _not_ re-run, because none of its inputs have changed.

Looking at this particular example:

```js
export const getSessionClient = createSelector(orm, getOrm, (session) => {
	return session.Session.first().client.ref;
});
```

This selector is returning the underlying plain JS object for the related Client instance.  `oneToOne` and `fk` relations are stored directly in that object.  However, `many` relations are stored in a separate "through table", not on the original object.  So, if you make a change to a relation on that Client instance, the core plain JS object will not have changed.  That means the inputs to `getClientAccountsQuerySet ` are still the same, and the output selector will not re-run.

**Comment by nealoke** [comment]
The `Client.accounts` is indeed a `many` relationship. Thanks for the clear explanation! I still feel like this should be doable though, or am I wrong in this thought?

**Comment by haveyaseen** [comment]
@nealoke Returning `QuerySet`s and `Model` instances from selectors is a bad idea for memoization. Version [0.14.0-rc.0](https://github.com/redux-orm/redux-orm/releases/tag/v0.14.0-rc.0) probably lets you accomplish your use case very easily. If you're still interested please try it out.
```js
const clientQuestions = createSelector(orm.Client.accounts.map(orm.Account.questions));
clientQuestions(state, 1); // (get all questions for the client with ID 1)
// Returns an array containing an array of questions for each of the client's accounts.
```
