### ISSUE TITLE
Videos on Redux ORM

### ISSUE THREAD

**Issue by rgautier2003** [redux-orm/redux-orm#254]
Hey guys know of anywhere one can get any videos on redux ORM intergrations? Cant seem to find anything on youtube, etc. 
Thanks

**Comment by haveyaseen** [comment]
It would definitely be great if there were some video tutorials, yeah :joy: I think a dedicated docs site is in order anyways so that's probably what I'll be tackling next, after simplifying our API for common use cases.

I'll be closing this issue so that we have a better overview. Do let me know if you find a video, though!
