### ISSUE TITLE
Cannot Copy / Clone SessionBoundModel correctly because of "attr" declarations

### ISSUE THREAD

**Issue by filozofer** [redux-orm/redux-orm#352]
I haven't find a way to copy / clone a SessionBoundModel correcty.
Let's say I receive a "client" in the props of my Component and I need to modify this client inside my component. Then, I must create a copy of it.
I try this:
`let client = {...props.client};`
or this:
`let client = Object.assign({}, props.client);`
But none of them works, the copy always miss the declared properties with "attr". I assume it's because my declared properties with attr inside my model make them non enumerable.

What can I do to copy with all the properties ?

Source of my hypothese: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/assign

**Comment by kirbydcool** [comment]
I'm not sure about the copying problem, but I think in general you shouldn't need to make copies of `SessionBoundModel` for a couple of reasons:
- Your selectors should generally return ref objects (`.ref` or `.toRefArray()`) rather than `SessionBoundModel`s. See https://github.com/redux-orm/redux-orm/issues/239#issuecomment-475645564 for more info.
- You shouldn't mutate your redux state directly, but use actions instead. Mark erikson, the maintainer of redux, provides some good resources here on a similar issue. https://github.com/redux-orm/redux-orm/issues/340#issuecomment-543347758

Hopefully that will steer you towards a better solution for your problem, but if you think you're in a unique situation where your approach makes sense, provide some more context around your use case and we can take a look.

**Comment by filozofer** [comment]
Thanx you @kirbydcool for your help. I was not aware of the `.ref` property !
I can't find a `.toRefArray()` in my case but `.ref` is ok !
I see this property is almost not mention in the main documentation of redux-orm. Maybe it will be usefull to do it ?

Here's the kind of code I end up just reading the doc (maybe too fast):
```
// Connect to redux store
export default connect(
    (state, props) => {
        return {
            client: Client(state).withId(props.route.match.params.id)
        }
    },
    { retrieveClient }
)(ClientOrganisationEdit);
```
Si my Component receive a "client" prop which was a SessionBoundModel rather than an Object.

This solution allow me to make shallow copy properly later without loosing some of the properties which is fine.
But I must also say that using the "ref" I miss the custom getters I've declared in my model (like a getFullname which a concatenation of multiple field for example).

Anyway, thanx you for this !
