### ISSUE TITLE
Bulk Fetch and Set

### ISSUE THREAD

**Issue by mbrahimi617** [redux-orm/redux-orm#419]
So from what I can tell it looks like there's a bulk delete method for querysets, however, I don't see anything for bulk creating by passing an array. Essentially, I have a fetch action which is responsible for populating the initial data, and I suppose I could for-each and create but honestly it's a little crude. I think querysets should definitely have a bulk create, delete, and a set which bulk creates upon bulk deleting in order to overwrite previous entries entirely.

**Comment by haveyaseen** [comment]
> I suppose I could for-each and create but honestly it's a little crude

Agreed, it's kind of strange. That approach also prevents optimization from our side. In theory it should be possible to perform bulk operations in a single transaction so that e.g. indexes are updated only once. A minimal implementation of a bulk create/delete for one-to-many relationships is outlined in **https://github.com/redux-orm/redux-orm/issues/291**.

> a set which bulk creates upon bulk deleting in order to overwrite previous entries entirely

This sounds a bit overkill to be honest. If individual fields are to be unset during merge maybe it would work to first fetch the model instances that are to be overwritten, replace every field of their `.ref` by `undefined`, merge them with the fetched entry and to then call `.update()` on the instances. One would need to test if immutable-ops supports a merger of `undefined` to unset values, though. Or use `null` instead. For a bulk update operation we would need to assume many things so I don't think that's something we should attempt to do for now.
